### ISSUE TITLE
Print Dialog Not Appearing for IE

### ISSUE THREAD

**Issue by jzk5360** [selemxmn/ngx-print#53]
Printing works as expected in Chrome and Firefox, but when the same page is accessed using IE 11 (Version: 11.3143.14393.0), clicking the Print button causes a preview window to appear (which looks as expected) but the Print dialog is not appearing.

**To Reproduce**
Attempt to print content using IE 11 browser.

**Expected behavior**
Expect to see a print dialogue window where user can select printer etc.

**Screenshot**
![No Print Dialogue Bug - Internet Explorer](https://user-images.githubusercontent.com/2655716/65704108-ef1be180-e053-11e9-9631-448cf0e4db80.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: IE
 - Version: 11.3143.14393.0

**Comment by spiko-md** [comment]
This seems to happen due to the arrow function in 
`<body onload="window.print(); setTimeout(()=>{ window.close(); }, 0)">`

**Comment by AcarMeel** [comment]
I'm experiencing the same issue. Where should I apply that fix? Name of the file? Thanks

**Comment by spiko-md** [comment]
> I'm experiencing the same issue. Where should I apply that fix? Name of the file? Thanks

Check out the `print()` method in src/lib/ngx-print.directive.ts

**Comment by MiroKov** [comment]
created a pull request: [https://github.com/selemxmn/ngx-print/pull/71](url)

**Comment by broem** [comment]
this should be fixed with @MiroKov 's pr

**Comment by MiroKov** [comment]
@broem 
Hi Ben, it wasn't fixed, probably because there was another timeout function in there that I missed.
Hopefully #74  shoud fix it.

**Comment by MiroKov** [comment]
With #74 will work. I have applied the change to the sintax in node_modules' scripts, and then it worked.
